### ISSUE TITLE
Branding for LEDS, AKSW, ...

### ISSUE THREAD

**Issue by k00ni** [AKSW/building-navigator#31]

**Comment by simeonackermann** [comment]
Shall I just put a LEDS/AKSW icon with linked to the github repo on the
top right?

Am 11.04.2017 um 14:24 schrieb Konrad Abicht:

**Comment by simeonackermann** [comment]
Latest commit https://github.com/AKSW/building-navigator/commit/035dc490ba885b8b6b96e221942b58834bd5d1bc adds a header on the top with LEDS logo.

I'm not sure if this is good, because 50px of the map are lost...

![bildschirmfoto von 2017-04-12 01-03-28](https://cloud.githubusercontent.com/assets/6428217/24934450/e285c086-1f1b-11e7-81a5-4833bb22485e.png)

**Comment by k00ni** [comment]
Hm, please let it that as it is for now, i have to think about it further. Let us talk about it in May.
