### ISSUE TITLE
Connect Buildingnavigator to final city-infrastructure.

### ISSUE THREAD

**Issue by k00ni** [AKSW/building-navigator#53]

**Comment by k00ni** [comment]
I got the (hopefully) final URL to the public SPARQL endpoint, which holds our place information.

**SPARQL Endpoint:** https://opendata.leipzig.de/virt-sparql
**Graph:** https://opendata.leipzig.de/bvlplaces/

Can you include these and give me a feedback, if there is any problem? Thank you!

**Comment by simeonackermann** [comment]
Sorry, I will only have time to try this on monday next week...

**Comment by k00ni** [comment]
No problem, looking forward to it.

**Comment by simeonackermann** [comment]
On my demo server asimeon.de I get this error:

> Failed to load https://opendata.leipzig.de/virt-sparql/: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://asimeon.de' is therefore not allowed access.

This is an error about [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) requests. 
Normally this means the server needs to add the origin or all (*) as allowed request (as described [here](http://vos.openlinksw.com/owiki/wiki/VOS/VirtTipsAndTricksCORsEnableSPARQLURLs))

Do you think we can request that?
Otherwise I don't know if we can fix this...

**Comment by k00ni** [comment]
The leading developer on the city-side @fkoestner posted me, that he had no problems. He used:

> curl -X POST https://opendata.leipzig.de/virt-sparql --data-urlencode "query=SELECT DISTINCT * FROM <https://opendata.leipzig.de/bvlplaces/> WHERE { ?s ?p ?o . } LIMIT 3" -H "Accept: application/sparql-results+json"

But he will check Virtuoso configuration and gets back to us soon.

**Comment by simeonackermann** [comment]
Its not a problem to directly call the virtuoso endpoint for me either. 
The problem occurs because the app is stored on our host behindertenverband-leipzig.de, and the request goes to another host. See here:

![](https://mdn.mozillademos.org/files/14295/CORS_principle.png)

This cross origin request is disallowed by browsers to improve security and needs to enabled by the seconds server (I didn't found another solution).

**Comment by fkoestner** [comment]
I checked the configuration of the virtuoso and the proxy. The proxy was missing a setting. So, cross origin requests are possible now.

**Comment by simeonackermann** [comment]
Jep, I can confirm, it works like a charm now!
Thanks for the fast help.

**Comment by simeonackermann** [comment]
Current commit in branch [round-4-navigation](https://github.com/AKSW/building-navigator/tree/round-4-navigation) implements the new endpoint

**Comment by k00ni** [comment]
Thanks @fkoestner!

@simeonackermann: Can you merge all branches into the final one for round 4? I would like to deploy your work next week, if possible.

**Comment by simeonackermann** [comment]
@k00ni all updates are merged into branch master now. To update the icons you should simply update the files in the `dist/images/bvl` folder.

**Comment by k00ni** [comment]
Can the other branches be deleted?

**Comment by simeonackermann** [comment]
Sure.
But we may keep the new branch [rdfstorejs](https://github.com/AKSW/building-navigator/tree/rdfstorejs) as standalone solution without a triple store.
